# Generated by Django 6.0.6 on 2026-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('costo_taller', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_mantenimiento', models.CharField(max_length=30)),
                ('repuestos_cambiados', models.TextField()),
                ('pdf_diagnostico', models.FileField(blank=True, null=True, upload_to='mantenimientos/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('tipo_combustible', models.CharField(max_length=30)),
                ('seguro_vigente', models.BooleanField(default=False)),
                ('anio_modelo', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
        ),
    ]
