# Generated by Django 4.2.20 on 2026-06-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=30)),
                ('tipo_combustible', models.CharField(max_length=20)),
                ('seguro_vigente', models.BooleanField(default=False)),
                ('anio_modelo', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('costo_taller', models.FloatField()),
                ('tipo_mantenimiento', models.CharField(max_length=20)),
                ('repuestos_cambiados', models.TextField()),
                ('pdf_diagnostico', models.FileField(blank=True, null=True, upload_to='diagnosticos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='flota.vehiculo')),
            ],
        ),
    ]
