# Generated by Django 6.0.6 on 2026-06-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='pdf_diagnostico',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
